name: CICD using Maven and tomcat
on:
 push:  # run when there is commit to repo
 workflow_dispatch:  # run manually
jobs:
 CICDjob:
   runs-on: ubuntu-latest
   steps:
    - name: Clone the repo on ubuntu server
      uses: actions/checkout@v4
    - name: Install Java and maven on ubuntu server
      uses: actions/setup-java@v4
      with:
       distribution: 'temurin'
       java-version: '11'
       cache: 'maven'
    - name: Build the code 
      run: mvn package
